import {sql} from "drizzle-orm";
import {integer,real,sqliteTable,text,uniqueIndex} from "drizzle-orm/sqlite-core";
export const businesses=sqliteTable("businesses",{id:text("id").primaryKey(),canonicalName:text("canonical_name").notNull(),locality:text("locality").notNull(),category:text("category").notNull(),latitude:real("latitude"),longitude:real("longitude"),verificationStatus:text("verification_status").notNull().default("candidate"),sourceEvidenceJson:text("source_evidence_json").notNull().default("[]"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const reviews=sqliteTable("reviews",{id:integer("id").primaryKey({autoIncrement:true}),businessId:text("business_id").notNull(),businessName:text("business_name").notNull(),answersJson:text("answers_json").notNull(),generatedDraft:text("generated_draft").notNull(),moderationStatus:text("moderation_status").notNull().default("pending"),visitConfidence:integer("visit_confidence").notNull().default(0),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const evidence=sqliteTable("evidence",{id:integer("id").primaryKey({autoIncrement:true}),reviewId:integer("review_id").notNull(),objectKey:text("object_key").notNull(),filename:text("filename").notNull(),contentType:text("content_type").notNull(),sizeBytes:integer("size_bytes").notNull(),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const answerBank=sqliteTable("answer_bank",{id:integer("id").primaryKey({autoIncrement:true}),scope:text("scope").notNull().default("general"),questionNormalized:text("question_normalized").notNull(),questionRaw:text("question_raw").notNull(),answerText:text("answer_text").notNull(),audioObjectKey:text("audio_object_key"),sourceProvider:text("source_provider"),hitCount:integer("hit_count").notNull().default(0),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`)},(table)=>[uniqueIndex("answer_bank_scope_question_idx").on(table.scope,table.questionNormalized)]);
// One row per (identifier, time window) — e.g. "assistant:1.2.3.4:29234567".
// Incremented atomically via onConflictDoUpdate; rows are cheap and never
// cleaned up, which is fine at MVP request volume (revisit if the table
// grows large enough to matter).
export const rateLimitHits=sqliteTable("rate_limit_hits",{bucketKey:text("bucket_key").primaryKey(),count:integer("count").notNull().default(0)});
